package com.fs.comm.mapper;

import java.util.List;
import java.util.Map;

import com.fs.comm.model.PhysicalChannel;

public interface PhysicalChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_physical_channel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_physical_channel
     *
     * @mbggenerated
     */
    int insert(PhysicalChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_physical_channel
     *
     * @mbggenerated
     */
    int insertSelective(PhysicalChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_physical_channel
     *
     * @mbggenerated
     */
    PhysicalChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_physical_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhysicalChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_physical_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhysicalChannel record);

    List<Map<String,Object>> getAllPhysicalChannelInfo(Map<String, Object> p);
    
    int delPhsicalChannelById(Integer id);
    
    int stopChannel(Integer id);
    
    int activateChannel(Integer id);
    
    int effectiveChannel(Integer id);
    
    int unEffectiveChannel(Integer id);
    
    int scrapChannel(Integer id);
    
    Map<String,Object> getPhsicalChannel(String cat_id);
    
}