package com.fs.comm.model;

public class AdbDebugServer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adbdebugserver.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adbdebugserver.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adbdebugserver.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adbdebugserver.adb_key
     *
     * @mbggenerated
     */
    private String adbKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adbdebugserver.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adbdebugserver.id
     *
     * @return the value of t_adbdebugserver.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adbdebugserver.id
     *
     * @param id the value for t_adbdebugserver.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adbdebugserver.ip
     *
     * @return the value of t_adbdebugserver.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adbdebugserver.ip
     *
     * @param ip the value for t_adbdebugserver.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adbdebugserver.port
     *
     * @return the value of t_adbdebugserver.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adbdebugserver.port
     *
     * @param port the value for t_adbdebugserver.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adbdebugserver.adb_key
     *
     * @return the value of t_adbdebugserver.adb_key
     *
     * @mbggenerated
     */
    public String getAdbKey() {
        return adbKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adbdebugserver.adb_key
     *
     * @param adbKey the value for t_adbdebugserver.adb_key
     *
     * @mbggenerated
     */
    public void setAdbKey(String adbKey) {
        this.adbKey = adbKey == null ? null : adbKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adbdebugserver.is_delete
     *
     * @return the value of t_adbdebugserver.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adbdebugserver.is_delete
     *
     * @param isDelete the value for t_adbdebugserver.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}