package com.fs.comm.model;



import java.util.Date;

public class AppEditions {
    private Integer id;
    private String name;
    private String packageName;
    private String version;
    private String appSize;
    private Integer downloadTimes;
    private String downloadUrl;
    private String lowestSystem;
    private Integer applicationId;
    private String applicationName;
    private Date createTime;
    private String isDelete;
    private String tempTime;
    
    
    
    public String getTempTime() {
		return tempTime;
	}

	public void setTempTime(String tempTime) {
		this.tempTime = tempTime;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.id
     *
     * @param id the value for t_app_editions.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.name
     *
     * @return the value of t_app_editions.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.name
     *
     * @param name the value for t_app_editions.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.package_name
     *
     * @return the value of t_app_editions.package_name
     *
     * @mbggenerated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.package_name
     *
     * @param packageName the value for t_app_editions.package_name
     *
     * @mbggenerated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.version
     *
     * @return the value of t_app_editions.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.version
     *
     * @param version the value for t_app_editions.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.app_size
     *
     * @return the value of t_app_editions.app_size
     *
     * @mbggenerated
     */
    public String getAppSize() {
        return appSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.app_size
     *
     * @param appSize the value for t_app_editions.app_size
     *
     * @mbggenerated
     */
    public void setAppSize(String appSize) {
        this.appSize = appSize == null ? null : appSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.download_times
     *
     * @return the value of t_app_editions.download_times
     *
     * @mbggenerated
     */
    public Integer getDownloadTimes() {
        return downloadTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.download_times
     *
     * @param downloadTimes the value for t_app_editions.download_times
     *
     * @mbggenerated
     */
    public void setDownloadTimes(Integer downloadTimes) {
        this.downloadTimes = downloadTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.download_url
     *
     * @return the value of t_app_editions.download_url
     *
     * @mbggenerated
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.download_url
     *
     * @param downloadUrl the value for t_app_editions.download_url
     *
     * @mbggenerated
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.lowest_system
     *
     * @return the value of t_app_editions.lowest_system
     *
     * @mbggenerated
     */
    public String getLowestSystem() {
        return lowestSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.lowest_system
     *
     * @param lowestSystem the value for t_app_editions.lowest_system
     *
     * @mbggenerated
     */
    public void setLowestSystem(String lowestSystem) {
        this.lowestSystem = lowestSystem == null ? null : lowestSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.application_id
     *
     * @return the value of t_app_editions.application_id
     *
     * @mbggenerated
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.application_id
     *
     * @param applicationId the value for t_app_editions.application_id
     *
     * @mbggenerated
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.application_name
     *
     * @return the value of t_app_editions.application_name
     *
     * @mbggenerated
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.application_name
     *
     * @param applicationName the value for t_app_editions.application_name
     *
     * @mbggenerated
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.create_time
     *
     * @return the value of t_app_editions.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.create_time
     *
     * @param createTime the value for t_app_editions.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_editions.is_delete
     *
     * @return the value of t_app_editions.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_editions.is_delete
     *
     * @param isDelete the value for t_app_editions.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}