package com.fs.comm.model;

import java.util.Date;

public class Card {
	
    private Long id;
    private String programmeCode;
    private String caCode;
    private String stbGroup;
    private String firmware;
    private String romversion;
    private Date lastTime;
    private String lastIp;
    private Long fixingId;
    private String isDelete;
    
    private String tempLastTime;
    private Integer numFlag;

  
    public Integer getNumFlag() {
		return numFlag;
	}

	public void setNumFlag(Integer numFlag) {
		this.numFlag = numFlag;
	}

	public String getTempLastTime() {
		return tempLastTime;
	}

	public void setTempLastTime(String tempLastTime) {
		this.tempLastTime = tempLastTime;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.id
     *
     * @param id the value for t_card.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.programme_code
     *
     * @return the value of t_card.programme_code
     *
     * @mbggenerated
     */
    public String getProgrammeCode() {
        return programmeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.programme_code
     *
     * @param programmeCode the value for t_card.programme_code
     *
     * @mbggenerated
     */
    public void setProgrammeCode(String programmeCode) {
        this.programmeCode = programmeCode == null ? null : programmeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.ca_code
     *
     * @return the value of t_card.ca_code
     *
     * @mbggenerated
     */
    public String getCaCode() {
        return caCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.ca_code
     *
     * @param caCode the value for t_card.ca_code
     *
     * @mbggenerated
     */
    public void setCaCode(String caCode) {
        this.caCode = caCode == null ? null : caCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.stb_group
     *
     * @return the value of t_card.stb_group
     *
     * @mbggenerated
     */
    public String getStbGroup() {
        return stbGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.stb_group
     *
     * @param stbGroup the value for t_card.stb_group
     *
     * @mbggenerated
     */
    public void setStbGroup(String stbGroup) {
        this.stbGroup = stbGroup == null ? null : stbGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.firmware
     *
     * @return the value of t_card.firmware
     *
     * @mbggenerated
     */
    public String getFirmware() {
        return firmware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.firmware
     *
     * @param firmware the value for t_card.firmware
     *
     * @mbggenerated
     */
    public void setFirmware(String firmware) {
        this.firmware = firmware == null ? null : firmware.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.romversion
     *
     * @return the value of t_card.romversion
     *
     * @mbggenerated
     */
    public String getRomversion() {
        return romversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.romversion
     *
     * @param romversion the value for t_card.romversion
     *
     * @mbggenerated
     */
    public void setRomversion(String romversion) {
        this.romversion = romversion == null ? null : romversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.last_time
     *
     * @return the value of t_card.last_time
     *
     * @mbggenerated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.last_time
     *
     * @param lastTime the value for t_card.last_time
     *
     * @mbggenerated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.last_ip
     *
     * @return the value of t_card.last_ip
     *
     * @mbggenerated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.last_ip
     *
     * @param lastIp the value for t_card.last_ip
     *
     * @mbggenerated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.fixing_id
     *
     * @return the value of t_card.fixing_id
     *
     * @mbggenerated
     */
    public Long getFixingId() {
        return fixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.fixing_id
     *
     * @param fixingId the value for t_card.fixing_id
     *
     * @mbggenerated
     */
    public void setFixingId(Long fixingId) {
        this.fixingId = fixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.is_delete
     *
     * @return the value of t_card.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.is_delete
     *
     * @param isDelete the value for t_card.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}