package com.fs.comm.model;

import java.util.Date;

public class Fixing {
	
    private Long id;
    private String fixingSn;
    private String type;
    private Date productionData;
    private Date openingData;
    private Date closingData;
    private String vender;
    private String version;
    private String userGroup;
    private String isDelete;
    private Long companyid;

  
    
    private String tempProductionData;
    private String tempOpeningData;
    private String tempClosingData;
    
    private Integer numFlag;
    
    
    
    
    public Integer getNumFlag() {
		return numFlag;
	}

	public void setNumFlag(Integer numFlag) {
		this.numFlag = numFlag;
	}

	public String getTempProductionData() {
		return tempProductionData;
	}

	public void setTempProductionData(String tempProductionData) {
		this.tempProductionData = tempProductionData;
	}

	public String getTempOpeningData() {
		return tempOpeningData;
	}

	public void setTempOpeningData(String tempOpeningData) {
		this.tempOpeningData = tempOpeningData;
	}

	public String getTempClosingData() {
		return tempClosingData;
	}

	public void setTempClosingData(String tempClosingData) {
		this.tempClosingData = tempClosingData;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.id
     *
     * @param id the value for t_fixing.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.fixing_sn
     *
     * @return the value of t_fixing.fixing_sn
     *
     * @mbggenerated
     */
    public String getFixingSn() {
        return fixingSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.fixing_sn
     *
     * @param fixingSn the value for t_fixing.fixing_sn
     *
     * @mbggenerated
     */
    public void setFixingSn(String fixingSn) {
        this.fixingSn = fixingSn == null ? null : fixingSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.type
     *
     * @return the value of t_fixing.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.type
     *
     * @param type the value for t_fixing.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.production_data
     *
     * @return the value of t_fixing.production_data
     *
     * @mbggenerated
     */
    public Date getProductionData() {
        return productionData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.production_data
     *
     * @param productionData the value for t_fixing.production_data
     *
     * @mbggenerated
     */
    public void setProductionData(Date productionData) {
        this.productionData = productionData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.opening_data
     *
     * @return the value of t_fixing.opening_data
     *
     * @mbggenerated
     */
    public Date getOpeningData() {
        return openingData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.opening_data
     *
     * @param openingData the value for t_fixing.opening_data
     *
     * @mbggenerated
     */
    public void setOpeningData(Date openingData) {
        this.openingData = openingData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.closing_data
     *
     * @return the value of t_fixing.closing_data
     *
     * @mbggenerated
     */
    public Date getClosingData() {
        return closingData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.closing_data
     *
     * @param closingData the value for t_fixing.closing_data
     *
     * @mbggenerated
     */
    public void setClosingData(Date closingData) {
        this.closingData = closingData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.vender
     *
     * @return the value of t_fixing.vender
     *
     * @mbggenerated
     */
    public String getVender() {
        return vender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.vender
     *
     * @param vender the value for t_fixing.vender
     *
     * @mbggenerated
     */
    public void setVender(String vender) {
        this.vender = vender == null ? null : vender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.version
     *
     * @return the value of t_fixing.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.version
     *
     * @param version the value for t_fixing.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.user_group
     *
     * @return the value of t_fixing.user_group
     *
     * @mbggenerated
     */
    public String getUserGroup() {
        return userGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.user_group
     *
     * @param userGroup the value for t_fixing.user_group
     *
     * @mbggenerated
     */
    public void setUserGroup(String userGroup) {
        this.userGroup = userGroup == null ? null : userGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.is_delete
     *
     * @return the value of t_fixing.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.is_delete
     *
     * @param isDelete the value for t_fixing.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fixing.companyid
     *
     * @return the value of t_fixing.companyid
     *
     * @mbggenerated
     */
    public Long getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fixing.companyid
     *
     * @param companyid the value for t_fixing.companyid
     *
     * @mbggenerated
     */
    public void setCompanyid(Long companyid) {
        this.companyid = companyid;
    }
}