package com.fs.comm.model;

import java.util.Date;

public class ImageVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image_video.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image_video.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image_video.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image_video.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image_video.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image_video.imageText_id
     *
     * @mbggenerated
     */
    private Integer imagetextId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image_video.id
     *
     * @return the value of t_image_video.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image_video.id
     *
     * @param id the value for t_image_video.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image_video.name
     *
     * @return the value of t_image_video.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image_video.name
     *
     * @param name the value for t_image_video.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image_video.url
     *
     * @return the value of t_image_video.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image_video.url
     *
     * @param url the value for t_image_video.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image_video.create_time
     *
     * @return the value of t_image_video.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image_video.create_time
     *
     * @param createTime the value for t_image_video.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image_video.is_delete
     *
     * @return the value of t_image_video.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image_video.is_delete
     *
     * @param isDelete the value for t_image_video.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image_video.imageText_id
     *
     * @return the value of t_image_video.imageText_id
     *
     * @mbggenerated
     */
    public Integer getImagetextId() {
        return imagetextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image_video.imageText_id
     *
     * @param imagetextId the value for t_image_video.imageText_id
     *
     * @mbggenerated
     */
    public void setImagetextId(Integer imagetextId) {
        this.imagetextId = imagetextId;
    }
}