package com.fs.comm.model;

public class LayoutSelectors {
   
    private Long id;

    private String name;

    private String focusedimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_layoutselectors.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_layoutselectors.id
     *
     * @return the value of t_layoutselectors.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_layoutselectors.id
     *
     * @param id the value for t_layoutselectors.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_layoutselectors.name
     *
     * @return the value of t_layoutselectors.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_layoutselectors.name
     *
     * @param name the value for t_layoutselectors.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_layoutselectors.focusedImg
     *
     * @return the value of t_layoutselectors.focusedImg
     *
     * @mbggenerated
     */
    public String getFocusedimg() {
        return focusedimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_layoutselectors.focusedImg
     *
     * @param focusedimg the value for t_layoutselectors.focusedImg
     *
     * @mbggenerated
     */
    public void setFocusedimg(String focusedimg) {
        this.focusedimg = focusedimg == null ? null : focusedimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_layoutselectors.is_delete
     *
     * @return the value of t_layoutselectors.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_layoutselectors.is_delete
     *
     * @param isDelete the value for t_layoutselectors.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}