package com.fs.comm.model;

import java.util.Date;

public class PhysicalChannel {
    private Integer id;
    private String name;
    private String type;
    private String level;
    private String sourceName;
    private String channelSource;
    private String format;
    private String codeCheck;
    private String channelUrl;
    private String status;
    private Date createTime;
    private String isDelete;
    private Integer channelId;
    private Integer channelNumber;
    private String activatedState;
    private String tempTime;
    
    

    public String getTempTime() {
		return tempTime;
	}

	public void setTempTime(String tempTime) {
		this.tempTime = tempTime;
	}

	public String getActivatedState() {
		return activatedState;
	}

	public void setActivatedState(String activatedState) {
		this.activatedState = activatedState;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.id
     *
     * @return the value of t_physical_channel.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.id
     *
     * @param id the value for t_physical_channel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.name
     *
     * @return the value of t_physical_channel.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.name
     *
     * @param name the value for t_physical_channel.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.type
     *
     * @return the value of t_physical_channel.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.type
     *
     * @param type the value for t_physical_channel.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.level
     *
     * @return the value of t_physical_channel.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.level
     *
     * @param level the value for t_physical_channel.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.source_name
     *
     * @return the value of t_physical_channel.source_name
     *
     * @mbggenerated
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.source_name
     *
     * @param sourceName the value for t_physical_channel.source_name
     *
     * @mbggenerated
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.channel_source
     *
     * @return the value of t_physical_channel.channel_source
     *
     * @mbggenerated
     */
    public String getChannelSource() {
        return channelSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.channel_source
     *
     * @param channelSource the value for t_physical_channel.channel_source
     *
     * @mbggenerated
     */
    public void setChannelSource(String channelSource) {
        this.channelSource = channelSource == null ? null : channelSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.format
     *
     * @return the value of t_physical_channel.format
     *
     * @mbggenerated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.format
     *
     * @param format the value for t_physical_channel.format
     *
     * @mbggenerated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.code_check
     *
     * @return the value of t_physical_channel.code_check
     *
     * @mbggenerated
     */
    public String getCodeCheck() {
        return codeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.code_check
     *
     * @param codeCheck the value for t_physical_channel.code_check
     *
     * @mbggenerated
     */
    public void setCodeCheck(String codeCheck) {
        this.codeCheck = codeCheck == null ? null : codeCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.channel_url
     *
     * @return the value of t_physical_channel.channel_url
     *
     * @mbggenerated
     */
    public String getChannelUrl() {
        return channelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.channel_url
     *
     * @param channelUrl the value for t_physical_channel.channel_url
     *
     * @mbggenerated
     */
    public void setChannelUrl(String channelUrl) {
        this.channelUrl = channelUrl == null ? null : channelUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.status
     *
     * @return the value of t_physical_channel.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.status
     *
     * @param status the value for t_physical_channel.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.create_time
     *
     * @return the value of t_physical_channel.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.create_time
     *
     * @param createTime the value for t_physical_channel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.is_delete
     *
     * @return the value of t_physical_channel.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.is_delete
     *
     * @param isDelete the value for t_physical_channel.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.channel_id
     *
     * @return the value of t_physical_channel.channel_id
     *
     * @mbggenerated
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.channel_id
     *
     * @param channelId the value for t_physical_channel.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_physical_channel.channel_number
     *
     * @return the value of t_physical_channel.channel_number
     *
     * @mbggenerated
     */
    public Integer getChannelNumber() {
        return channelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_physical_channel.channel_number
     *
     * @param channelNumber the value for t_physical_channel.channel_number
     *
     * @mbggenerated
     */
    public void setChannelNumber(Integer channelNumber) {
        this.channelNumber = channelNumber;
    }
}