package com.fs.comm.model;

public class Program {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.program_type
     *
     * @mbggenerated
     */
    private String programType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.clarity
     *
     * @mbggenerated
     */
    private String clarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.seat
     *
     * @mbggenerated
     */
    private Integer seat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.show_type
     *
     * @mbggenerated
     */
    private String showType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.suppot_type
     *
     * @mbggenerated
     */
    private String suppotType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.copyright
     *
     * @mbggenerated
     */
    private String copyright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.shim
     *
     * @mbggenerated
     */
    private String shim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.shim_url
     *
     * @mbggenerated
     */
    private String shimUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.preferences
     *
     * @mbggenerated
     */
    private String preferences;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.number
     *
     * @mbggenerated
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.column_id
     *
     * @mbggenerated
     */
    private Integer columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_program.columnType_id
     *
     * @mbggenerated
     */
    private Long columntypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.id
     *
     * @return the value of t_program.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.id
     *
     * @param id the value for t_program.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.name
     *
     * @return the value of t_program.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.name
     *
     * @param name the value for t_program.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.type
     *
     * @return the value of t_program.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.type
     *
     * @param type the value for t_program.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.content
     *
     * @return the value of t_program.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.content
     *
     * @param content the value for t_program.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.status
     *
     * @return the value of t_program.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.status
     *
     * @param status the value for t_program.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.program_type
     *
     * @return the value of t_program.program_type
     *
     * @mbggenerated
     */
    public String getProgramType() {
        return programType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.program_type
     *
     * @param programType the value for t_program.program_type
     *
     * @mbggenerated
     */
    public void setProgramType(String programType) {
        this.programType = programType == null ? null : programType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.clarity
     *
     * @return the value of t_program.clarity
     *
     * @mbggenerated
     */
    public String getClarity() {
        return clarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.clarity
     *
     * @param clarity the value for t_program.clarity
     *
     * @mbggenerated
     */
    public void setClarity(String clarity) {
        this.clarity = clarity == null ? null : clarity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.seat
     *
     * @return the value of t_program.seat
     *
     * @mbggenerated
     */
    public Integer getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.seat
     *
     * @param seat the value for t_program.seat
     *
     * @mbggenerated
     */
    public void setSeat(Integer seat) {
        this.seat = seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.show_type
     *
     * @return the value of t_program.show_type
     *
     * @mbggenerated
     */
    public String getShowType() {
        return showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.show_type
     *
     * @param showType the value for t_program.show_type
     *
     * @mbggenerated
     */
    public void setShowType(String showType) {
        this.showType = showType == null ? null : showType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.suppot_type
     *
     * @return the value of t_program.suppot_type
     *
     * @mbggenerated
     */
    public String getSuppotType() {
        return suppotType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.suppot_type
     *
     * @param suppotType the value for t_program.suppot_type
     *
     * @mbggenerated
     */
    public void setSuppotType(String suppotType) {
        this.suppotType = suppotType == null ? null : suppotType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.copyright
     *
     * @return the value of t_program.copyright
     *
     * @mbggenerated
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.copyright
     *
     * @param copyright the value for t_program.copyright
     *
     * @mbggenerated
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright == null ? null : copyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.shim
     *
     * @return the value of t_program.shim
     *
     * @mbggenerated
     */
    public String getShim() {
        return shim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.shim
     *
     * @param shim the value for t_program.shim
     *
     * @mbggenerated
     */
    public void setShim(String shim) {
        this.shim = shim == null ? null : shim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.shim_url
     *
     * @return the value of t_program.shim_url
     *
     * @mbggenerated
     */
    public String getShimUrl() {
        return shimUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.shim_url
     *
     * @param shimUrl the value for t_program.shim_url
     *
     * @mbggenerated
     */
    public void setShimUrl(String shimUrl) {
        this.shimUrl = shimUrl == null ? null : shimUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.preferences
     *
     * @return the value of t_program.preferences
     *
     * @mbggenerated
     */
    public String getPreferences() {
        return preferences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.preferences
     *
     * @param preferences the value for t_program.preferences
     *
     * @mbggenerated
     */
    public void setPreferences(String preferences) {
        this.preferences = preferences == null ? null : preferences.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.number
     *
     * @return the value of t_program.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.number
     *
     * @param number the value for t_program.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.is_delete
     *
     * @return the value of t_program.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.is_delete
     *
     * @param isDelete the value for t_program.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.column_id
     *
     * @return the value of t_program.column_id
     *
     * @mbggenerated
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.column_id
     *
     * @param columnId the value for t_program.column_id
     *
     * @mbggenerated
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_program.columnType_id
     *
     * @return the value of t_program.columnType_id
     *
     * @mbggenerated
     */
    public Long getColumntypeId() {
        return columntypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_program.columnType_id
     *
     * @param columntypeId the value for t_program.columnType_id
     *
     * @mbggenerated
     */
    public void setColumntypeId(Long columntypeId) {
        this.columntypeId = columntypeId;
    }
}