package com.fs.comm.model;

public class UiPwd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uipwd.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uipwd.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uipwd.val
     *
     * @mbggenerated
     */
    private String val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uipwd.is_detele
     *
     * @mbggenerated
     */
    private String isDetele;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uipwd.id
     *
     * @return the value of t_uipwd.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uipwd.id
     *
     * @param id the value for t_uipwd.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uipwd.name
     *
     * @return the value of t_uipwd.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uipwd.name
     *
     * @param name the value for t_uipwd.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uipwd.val
     *
     * @return the value of t_uipwd.val
     *
     * @mbggenerated
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uipwd.val
     *
     * @param val the value for t_uipwd.val
     *
     * @mbggenerated
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uipwd.is_detele
     *
     * @return the value of t_uipwd.is_detele
     *
     * @mbggenerated
     */
    public String getIsDetele() {
        return isDetele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uipwd.is_detele
     *
     * @param isDetele the value for t_uipwd.is_detele
     *
     * @mbggenerated
     */
    public void setIsDetele(String isDetele) {
        this.isDetele = isDetele == null ? null : isDetele.trim();
    }
}