package com.fs.comm.model;

public class UserTokenToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.token_code
     *
     * @mbggenerated
     */
    private String tokenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.id
     *
     * @return the value of t_token.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.id
     *
     * @param id the value for t_token.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.token_code
     *
     * @return the value of t_token.token_code
     *
     * @mbggenerated
     */
    public String getTokenCode() {
        return tokenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.token_code
     *
     * @param tokenCode the value for t_token.token_code
     *
     * @mbggenerated
     */
    public void setTokenCode(String tokenCode) {
        this.tokenCode = tokenCode == null ? null : tokenCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.user_id
     *
     * @return the value of t_token.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.user_id
     *
     * @param userId the value for t_token.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}